import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Sync documentation from docs/ to webui/src/docs/
import { syncDocs } from './generate-mdx-docs.js'
import { generateNavigation } from './generate-nav-from-docs.js'

syncDocs()
generateNavigation()

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')
const coreDir = resolve(projectRoot, '..', 'core')
const destFile = resolve(projectRoot, 'src', 'config', 'webui-app-contents.ts')

const configFiles = [
  'github-labels-config.ts',
  'repos.json',
  'microscope-list.ts',
  'webui-config.ts',
]

for (const file of configFiles) {
  const path = resolve(coreDir, file)
  if (!existsSync(path)) {
    console.error(`Config file not found: ${path}`)
    process.exit(1)
  }
}

const githubLabelsContent = readFileSync(resolve(coreDir, 'github-labels-config.ts'), 'utf-8')
const reposJsonContent = readFileSync(resolve(coreDir, 'repos.json'), 'utf-8')
const microscopeListContent = readFileSync(resolve(coreDir, 'microscope-list.ts'), 'utf-8')
const webuiConfigContent = readFileSync(resolve(coreDir, 'webui-config.ts'), 'utf-8')

const reposJson = JSON.parse(reposJsonContent)

function generateReposAndRefsFromJson(): string {
  const diamondLightSourceOrg = reposJson.organizations.find(
    (org: { name: string }) => org.name === 'DiamondLightSource'
  )
  const fragmentScreenOrg = reposJson.organizations.find(
    (org: { name: string }) => org.name === 'FragmentScreen'
  )
  const ariaPHPOrg = reposJson.organizations.find(
    (org: { name: string }) => org.name === 'aria-php'
  )

  const mapRepo = (repo: {
    name: string
    description: string
    urls: { https: string; ssh: string }
    tags?: string[]
    ownership?: string
    required?: boolean
  }) => ({
    name: repo.name,
    description: repo.description,
    urls: repo.urls,
    tags: repo.tags,
    ownership: repo.ownership,
    required: repo.required,
  })

  return `interface RepoUrls {
  https: string
  ssh: string
}

interface Repository {
  name: string
  description: string
  urls: RepoUrls
  tags?: string[]
  ownership?: 'full' | 'reference-only'
  required?: boolean
}

interface OrgRepos {
  org: string
  orgUrl: string
  repos: Repository[]
}

interface ExternalLinks {
  docs: string
  projectBoard: string
}

interface ReposAndRefsConfig {
  links: ExternalLinks
  repositories: OrgRepos[]
}

const reposAndRefsConfig: ReposAndRefsConfig = {
  links: {
    docs: ${JSON.stringify(reposJson.links.docs)},
    projectBoard: ${JSON.stringify(reposJson.links.projectBoard)},
  },
  repositories: [
    {
      org: 'DiamondLightSource',
      orgUrl: ${JSON.stringify(diamondLightSourceOrg?.url ?? 'https://github.com/DiamondLightSource')},
      repos: ${JSON.stringify((diamondLightSourceOrg?.repos ?? []).map(mapRepo), null, 8).replace(/\n/g, '\n      ')},
    },
    {
      org: 'FragmentScreen',
      orgUrl: ${JSON.stringify(fragmentScreenOrg?.url ?? 'https://github.com/FragmentScreen')},
      repos: ${JSON.stringify((fragmentScreenOrg?.repos ?? []).map(mapRepo), null, 8).replace(/\n/g, '\n      ')},
    },
    {
      org: 'aria-php',
      orgUrl: ${JSON.stringify(ariaPHPOrg?.url ?? 'https://gitlab.com/aria-php')},
      repos: ${JSON.stringify((ariaPHPOrg?.repos ?? []).map(mapRepo), null, 8).replace(/\n/g, '\n      ')},
    },
  ],
}`
}

const aggregatedContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/prebuild.ts from:
 * - core/github-labels-config.ts
 * - core/repos.json (source of truth for repository definitions)
 * - core/microscope-list.ts
 * - core/webui-config.ts
 *
 * Edit the source files in core/ and run 'npm run prebuild' to regenerate.
 */

// =============================================================================
// GitHub Labels Config
// =============================================================================

${stripExportsAndComments(githubLabelsContent, 'GitHubLabelsConfig', 'githubLabelsConfig')}

// =============================================================================
// Repos and Refs (generated from repos.json)
// =============================================================================

${generateReposAndRefsFromJson()}

// =============================================================================
// Microscope List
// =============================================================================

${stripExportsAndComments(microscopeListContent, 'CryoEMInstrument', 'microscopeList')}

// =============================================================================
// WebUI Config
// =============================================================================

${stripExportsAndComments(webuiConfigContent, 'WebUiConfig', 'webUiConfig')}

// =============================================================================
// Aggregated App Contents
// =============================================================================

export interface WebUiAppContents {
  githubLabels: GitHubLabelsConfig
  repos: ReposAndRefsConfig
  microscopes: CryoEMInstrument[]
  config: WebUiConfig
  featureFlags: FeatureFlags
}

export const webUiAppContents: WebUiAppContents = {
  githubLabels: githubLabelsConfig,
  repos: reposAndRefsConfig,
  microscopes: microscopeList,
  config: webUiConfig,
  featureFlags: featureFlags,
}

export default webUiAppContents
`

function stripExportsAndComments(content: string, _mainType: string, _mainExport: string): string {
  return content
    .replace(/\/\*\*[\s\S]*?\*\/\n*/g, '')
    .replace(/^export default.*\n?/gm, '')
    .replace(/^export /gm, '')
    .trim()
}

writeFileSync(destFile, aggregatedContent)
console.log(`Generated ${destFile}`)
