import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')
const coreDir = resolve(projectRoot, '..', 'core')
const destFile = resolve(projectRoot, 'src', 'config', 'webui-app-contents.ts')

const configFiles = [
  'github-tags-config.ts',
  'repos-and-refs.ts',
  'microscope-list.ts',
  'webui-config.ts',
]

for (const file of configFiles) {
  const path = resolve(coreDir, file)
  if (!existsSync(path)) {
    console.error(`Config file not found: ${path}`)
    process.exit(1)
  }
}

const githubTagsContent = readFileSync(resolve(coreDir, 'github-tags-config.ts'), 'utf-8')
const reposAndRefsContent = readFileSync(resolve(coreDir, 'repos-and-refs.ts'), 'utf-8')
const microscopeListContent = readFileSync(resolve(coreDir, 'microscope-list.ts'), 'utf-8')
const webuiConfigContent = readFileSync(resolve(coreDir, 'webui-config.ts'), 'utf-8')

const aggregatedContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/prebuild.ts from:
 * - core/github-tags-config.ts
 * - core/repos-and-refs.ts
 * - core/microscope-list.ts
 * - core/webui-config.ts
 *
 * Edit the source files in core/ and run 'npm run prebuild' to regenerate.
 */

// =============================================================================
// GitHub Tags Config
// =============================================================================

${stripExportsAndComments(githubTagsContent, 'GitHubTagsConfig', 'githubTagsConfig')}

// =============================================================================
// Repos and Refs
// =============================================================================

${stripExportsAndComments(reposAndRefsContent, 'ReposAndRefsConfig', 'reposAndRefsConfig')}

// =============================================================================
// Microscope List
// =============================================================================

${stripExportsAndComments(microscopeListContent, 'CryoEMInstrument', 'microscopeList')}

// =============================================================================
// WebUI Config
// =============================================================================

${stripExportsAndComments(webuiConfigContent, 'WebUiConfig', 'webUiConfig')}

// =============================================================================
// Aggregated App Contents
// =============================================================================

export interface WebUiAppContents {
  githubTags: GitHubTagsConfig
  repos: ReposAndRefsConfig
  microscopes: CryoEMInstrument[]
  config: WebUiConfig
  featureFlags: FeatureFlags
}

export const webUiAppContents: WebUiAppContents = {
  githubTags: githubTagsConfig,
  repos: reposAndRefsConfig,
  microscopes: microscopeList,
  config: webUiConfig,
  featureFlags: featureFlags,
}

export default webUiAppContents
`

function stripExportsAndComments(content: string, _mainType: string, _mainExport: string): string {
  return content
    .replace(/\/\*\*[\s\S]*?\*\/\n*/g, '')
    .replace(/^export default.*\n?/gm, '')
    .replace(/^export /gm, '')
    .trim()
}

writeFileSync(destFile, aggregatedContent)
console.log(`Generated ${destFile}`)
