# Auto-labeling configuration for PRs based on changed files
# Labels must exist in core/github-labels-config.ts to be synced properly

# Component labels (packages)
component:epuplayer:
  - changed-files:
      - any-glob-to-any-file: packages/smartem-epuplayer/**

component:smartem-workspace:
  - changed-files:
      - any-glob-to-any-file: packages/smartem-workspace/**

# Devtools sub-component labels
smartem-devtools:webui:
  - changed-files:
      - any-glob-to-any-file: webui/**

smartem-devtools:claude:
  - changed-files:
      - any-glob-to-any-file: claude-code/**

smartem-devtools:e2e-test:
  - changed-files:
      - any-glob-to-any-file: tests/e2e/**

# Type-of-work labels
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - '**/*.md'

devops:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - scripts/k8s/**
          - scripts/github/**
          - k8s/**
