/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/generate-nav-from-docs.ts from the docs/ directory structure.
 * Edit the docs/ folder structure and run 'npm run prebuild' to regenerate.
 */

export interface NavItem {
  title: string
  href: string
  children?: NavItem[]
}

export const docsNavigation: NavItem[] = [
  {
    title: 'Agent',
    href: '/docs/agent',
    children: [
      {
        title: 'SmartEM Agent CLI Reference',
        href: '/docs/agent/cli-reference',
      },
      {
        title: 'Run SmartEM Agent (EPU Agent)',
        href: '/docs/agent/deployment',
      },
      {
        title: 'SmartEM CLI Troubleshooting Guide',
        href: '/docs/agent/troubleshooting',
      },
    ],
  },
  {
    title: 'Architecture',
    href: '/docs/architecture',
  },
  {
    title: 'Athena Integration',
    href: '/docs/athena',
  },
  {
    title: 'Backend',
    href: '/docs/backend',
    children: [
      {
        title: 'Using the API Documentation',
        href: '/docs/backend/api-documentation',
      },
      {
        title: 'Run SmartEM Backend',
        href: '/docs/backend/api-server',
      },
      {
        title: 'Database Migrations',
        href: '/docs/backend/database',
      },
      {
        title: 'How to Use the SmartEM API Client',
        href: '/docs/backend/http-api-client',
      },
    ],
  },
  {
    title: 'Decision Records',
    href: '/docs/decision-records',
    children: [
      {
        title: 'Decisions',
        href: '/docs/decision-records/decisions',
        children: [
          {
            title: '1. Record architecture decisions',
            href: '/docs/decision-records/decisions/0001-record-architecture-decisions',
          },
          {
            title: '2. Adopt python-copier-template for project structure',
            href: '/docs/decision-records/decisions/0002-switched-to-python-copier-template',
          },
          {
            title: '3. Short descriptive title',
            href: '/docs/decision-records/decisions/0003-message-queue-message-grouping',
          },
          {
            title: '3. No dependency on python-zocalo',
            href: '/docs/decision-records/decisions/0004-zocalo-dependency-free',
          },
          {
            title: '5. Use detect-secrets for secret scanning',
            href: '/docs/decision-records/decisions/0005-detect-secrets-for-secret-scanning',
          },
          {
            title: '6. Use Sealed Secrets for Kubernetes secrets management',
            href: '/docs/decision-records/decisions/0006-sealed-secrets-kubernetes-secrets-management',
          },
          {
            title: '7. Eliminate circular dependency between smartem_api and smartem_backend',
            href: '/docs/decision-records/decisions/0007-eliminate-smartem-api-circular-dependency',
          },
          {
            title: '8. Backend-to-Agent Communication Protocol Selection',
            href: '/docs/decision-records/decisions/0008-backend-to-agent-communication-architecture',
          },
          {
            title: 'ADR 0009: Commit Generated Route Tree to Version Control',
            href: '/docs/decision-records/decisions/0009-commit-generated-route-tree',
          },
          {
            title: '11. Remove python-copier-template',
            href: '/docs/decision-records/decisions/0011-remove-python-copier-template',
          },
          {
            title: '12. Audience-Based Documentation Structure',
            href: '/docs/decision-records/decisions/0012-audience-based-documentation-structure',
          },
          {
            title: '13. EPUPlayer Release Strategy',
            href: '/docs/decision-records/decisions/0013-epuplayer-release-strategy',
          },
        ],
      },
      {
        title: 'Backend-to-Agent Communication System Design',
        href: '/docs/decision-records/backend-agent-communication-system-design',
      },
      {
        title: 'Architectural Decision Records',
        href: '/docs/decision-records/decisions',
      },
      {
        title: 'EPU Output Directory Structure',
        href: '/docs/decision-records/epu-data-structures',
      },
      {
        title: 'SmartEM Agent: Design Specification',
        href: '/docs/decision-records/smartem-agent-design',
      },
      {
        title: 'Developer Guide: smartem-workspace',
        href: '/docs/decision-records/smartem-workspace-developer-guide',
      },
      {
        title: 'Technical Notes',
        href: '/docs/decision-records/technical-notes',
      },
    ],
  },
  {
    title: 'Development',
    href: '/docs/development',
    children: [
      {
        title: 'Contributing',
        href: '/docs/development/contributing',
      },
      {
        title: 'End-to-End Development Test Runs',
        href: '/docs/development/e2e-simulation',
      },
      {
        title: 'Generate Documentation',
        href: '/docs/development/generate-docs',
      },
      {
        title: 'How to Sync GitHub Labels',
        href: '/docs/development/github-labels',
      },
      {
        title: 'Using SmartEM MCP Interface',
        href: '/docs/development/mcp-interface',
      },
      {
        title: 'Development Tools',
        href: '/docs/development/tools',
      },
    ],
  },
  {
    title: 'Getting Started',
    href: '/docs/getting-started',
    children: [
      {
        title: 'Installation',
        href: '/docs/getting-started/for-developers',
      },
    ],
  },
  {
    title: 'Operations',
    href: '/docs/operations',
    children: [
      {
        title: 'Container User Configuration',
        href: '/docs/operations/container-user-configuration',
      },
      {
        title: 'Containerization',
        href: '/docs/operations/containerization',
      },
      {
        title: 'Configure Environment Variables',
        href: '/docs/operations/environment-variables',
      },
      {
        title: 'Managing Kubernetes Secrets',
        href: '/docs/operations/kubernetes-secrets',
      },
      {
        title: 'Kubernetes Deployment',
        href: '/docs/operations/kubernetes',
      },
      {
        title: 'Configure Logging and Verbosity',
        href: '/docs/operations/logging',
      },
      {
        title: 'PyPI Token Setup for CI/CD',
        href: '/docs/operations/publish-smartem-workspace-to-pypi',
      },
      {
        title: 'Run in a container',
        href: '/docs/operations/run-container',
      },
      {
        title: 'Setup SmartEM Workspace',
        href: '/docs/operations/setup-smartem-workspace',
      },
    ],
  },
  {
    title: 'Database Schema Drift Prevention',
    href: '/docs/database-schema-drift-prevention',
  },
  {
    title: 'Glossary',
    href: '/docs/glossary',
  },
]
