apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartem-decisions

resources:
- keycloak.yaml

configMapGenerator:
- name: keycloak-realm
  files:
  - dls-realm.json

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/part-of: smartem-keycloak-mock
