/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/prebuild.ts from:
 * - core/github-tags-config.ts
 * - core/repos-and-refs.ts
 * - core/microscope-list.ts
 * - core/webui-config.ts
 *
 * Edit the source files in core/ and run 'npm run prebuild' to regenerate.
 */

// =============================================================================
// GitHub Tags Config
// =============================================================================

interface GitHubLabel {
  name: string
  description: string
  color: string // 6-char hex without #
}

interface GitHubTagsConfig {
  typesOfWork: GitHubLabel[]
  systemComponents: GitHubLabel[]
}

const typesOfWork: GitHubLabel[] = [
  { name: 'documentation', description: 'Improvements or additions to project documentation', color: '0d6d6e' },
  { name: 'testing', description: 'Writing, updating, or fixing automated tests', color: '2da44e' },
  { name: 'bugfixing', description: 'Fixing defects or unexpected behavior in existing code', color: 'cf222e' },
  { name: 'development', description: 'New features or functionality implementation', color: '8250df' },
  { name: 'refactoring', description: 'Code restructuring without changing external behavior', color: 'bc4c00' },
  { name: 'research', description: 'Investigation, spikes, or proof-of-concept work', color: '0598bd' },
  { name: 'devops', description: 'CI/CD, deployment, infrastructure, or tooling work', color: '57606a' },
  { name: 'security', description: 'Security fixes, audits, or vulnerability remediation', color: 'a40e26' },
  { name: 'admin', description: 'Project maintenance, dependency updates, or housekeeping', color: '7c4a03' },
  { name: 'enhancement', description: 'Minor improvements to existing functionality', color: '1b7c83' },
]

const systemComponents: GitHubLabel[] = [
  // smartem-backend family (ocean blue scale: #0a3069 -> #0550ae -> #218bff)
  { name: 'smartem-backend', description: 'Core backend services, messaging, and persistence layer', color: '0a3069' },
  { name: 'smartem-backend:db', description: 'Database schema, migrations, and data layer changes', color: '0550ae' },
  { name: 'smartem-backend:api', description: 'REST API endpoints and HTTP interface changes', color: '218bff' },

  // smartem-agent (gold - standalone)
  { name: 'smartem-agent', description: 'EPU workstation agent for microscope integration', color: '9a6700' },

  // smartem-frontend (green - standalone)
  { name: 'smartem-frontend', description: 'User-facing web UI for acquisition sessions and ML decisions', color: '1a7f37' },

  // smartem-aria-connector (purple - standalone)
  { name: 'smartem-aria-connector', description: 'ARIA deposition integration via FandanGO plugin', color: '6639ba' },

  // smartem-devtools family (warm pink scale: #99154b -> #bf3989 -> #db61a2 -> #f09bc8)
  { name: 'smartem-devtools', description: 'Developer tooling, documentation, and workspace configuration', color: '99154b' },
  { name: 'smartem-devtools:webui', description: 'Developer dashboard web interface', color: 'bf3989' },
  { name: 'smartem-devtools:claude', description: 'Claude Code configuration, skills, and prompts', color: 'db61a2' },
  { name: 'smartem-devtools:e2e-test', description: 'End-to-end testing infrastructure and scenarios', color: 'f09bc8' },
]

const githubTagsConfig: GitHubTagsConfig = {
  typesOfWork,
  systemComponents,
}

// =============================================================================
// Repos and Refs
// =============================================================================

interface RepoUrls {
  https: string
  ssh: string
}

interface Repository {
  name: string
  description: string
  urls: RepoUrls
}

interface OrgRepos {
  org: string
  orgUrl: string
  repos: Repository[]
}

interface ExternalLinks {
  docs: string
  projectBoard: string
}

interface ReposAndRefsConfig {
  links: ExternalLinks
  repositories: OrgRepos[]
}

const diamondLightSourceRepos: Repository[] = [
  {
    name: 'smartem-decisions',
    description: 'Central system controller - backbone, messaging router, persistence, auth',
    urls: {
      https: 'https://github.com/DiamondLightSource/smartem-decisions.git',
      ssh: 'git@github.com:DiamondLightSource/smartem-decisions.git',
    },
  },
  {
    name: 'smartem-frontend',
    description: 'Web UI for SmartEM - user-facing view of acquisition sessions and ML decisions',
    urls: {
      https: 'https://github.com/DiamondLightSource/smartem-frontend.git',
      ssh: 'git@github.com:DiamondLightSource/smartem-frontend.git',
    },
  },
  {
    name: 'smartem-devtools',
    description: 'Developer tooling, documentation, and workspace configuration',
    urls: {
      https: 'https://github.com/DiamondLightSource/smartem-devtools.git',
      ssh: 'git@github.com:DiamondLightSource/smartem-devtools.git',
    },
  },
  {
    name: 'fandanGO-cryoem-dls',
    description: 'DLS facility plugin for FandanGO - bridges SmartEM to ARIA',
    urls: {
      https: 'https://github.com/DiamondLightSource/fandanGO-cryoem-dls.git',
      ssh: 'git@github.com:DiamondLightSource/fandanGO-cryoem-dls.git',
    },
  },
  {
    name: 'cryoem-services',
    description: 'Processing execution layer for cryo-EM data pipelines (reference-only)',
    urls: {
      https: 'https://github.com/DiamondLightSource/cryoem-services.git',
      ssh: 'git@github.com:DiamondLightSource/cryoem-services.git',
    },
  },
]

const gitlabAriaPHPRepos: Repository[] = [
  {
    name: 'data-deposition-api',
    description: 'ARIA GraphQL/REST API for metadata deposition (primary)',
    urls: {
      https: 'https://gitlab.com/aria-php/data-deposition-api.git',
      ssh: 'git@gitlab.com:aria-php/data-deposition-api.git',
    },
  },
  {
    name: 'aria-graphql-client',
    description: 'PHP library for communicating with ARIA GraphQL API',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-graphql-client.git',
      ssh: 'git@gitlab.com:aria-php/aria-graphql-client.git',
    },
  },
  {
    name: 'aria-elasticsearch-client',
    description: 'Elasticsearch client for ARIA search records',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-elasticsearch-client.git',
      ssh: 'git@gitlab.com:aria-php/aria-elasticsearch-client.git',
    },
  },
  {
    name: 'aria-rest',
    description: 'REST API framework for defining versioned APIs',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-rest.git',
      ssh: 'git@gitlab.com:aria-php/aria-rest.git',
    },
  },
  {
    name: 'aria-storage-interface',
    description: 'Storage provider interface',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-storage-interface.git',
      ssh: 'git@gitlab.com:aria-php/aria-storage-interface.git',
    },
  },
  {
    name: 'aria-webhooks',
    description: 'Standard webhook payload format for ARIA platform',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-webhooks.git',
      ssh: 'git@gitlab.com:aria-php/aria-webhooks.git',
    },
  },
  {
    name: 'aria-incoming-email',
    description: 'Incoming email message routing',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-incoming-email.git',
      ssh: 'git@gitlab.com:aria-php/aria-incoming-email.git',
    },
  },
  {
    name: 'aria-mailer',
    description: 'Email wrapper (PHPMailer + Swiftmailer)',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-mailer.git',
      ssh: 'git@gitlab.com:aria-php/aria-mailer.git',
    },
  },
  {
    name: 'aria-mailgun-webhooks',
    description: 'Mailgun webhook event parser',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-mailgun-webhooks.git',
      ssh: 'git@gitlab.com:aria-php/aria-mailgun-webhooks.git',
    },
  },
  {
    name: 'aria-invite-users',
    description: 'User invitation framework',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-invite-users.git',
      ssh: 'git@gitlab.com:aria-php/aria-invite-users.git',
    },
  },
  {
    name: 'aria-data-subscription',
    description: 'Data source subscription framework for feeds',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-data-subscription.git',
      ssh: 'git@gitlab.com:aria-php/aria-data-subscription.git',
    },
  },
  {
    name: 'aria-stats',
    description: 'Performance statistics monitoring',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-stats.git',
      ssh: 'git@gitlab.com:aria-php/aria-stats.git',
    },
  },
  {
    name: 'aria-site-logger',
    description: 'Monolog plugin for ARIA site logging',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-site-logger.git',
      ssh: 'git@gitlab.com:aria-php/aria-site-logger.git',
    },
  },
  {
    name: 'aria-service-ai',
    description: 'Service AI library',
    urls: {
      https: 'https://gitlab.com/aria-php/aria-service-ai.git',
      ssh: 'git@gitlab.com:aria-php/aria-service-ai.git',
    },
  },
  {
    name: 'keycloak-api',
    description: 'PHP bindings for Keycloak Account API',
    urls: {
      https: 'https://gitlab.com/aria-php/keycloak-api.git',
      ssh: 'git@gitlab.com:aria-php/keycloak-api.git',
    },
  },
  {
    name: 'doi-package',
    description: 'DOI microservice client',
    urls: {
      https: 'https://gitlab.com/aria-php/doi-package.git',
      ssh: 'git@gitlab.com:aria-php/doi-package.git',
    },
  },
  {
    name: 'molgenis-php-client',
    description: 'PHP client for Molgenis database',
    urls: {
      https: 'https://gitlab.com/aria-php/molgenis-php-client.git',
      ssh: 'git@gitlab.com:aria-php/molgenis-php-client.git',
    },
  },
  {
    name: 'shibboleth-idp-dockerized',
    description: 'Dockerized Shibboleth IdP (identity federation)',
    urls: {
      https: 'https://gitlab.com/aria-php/shibboleth-idp-dockerized.git',
      ssh: 'git@gitlab.com:aria-php/shibboleth-idp-dockerized.git',
    },
  },
  {
    name: 'rtd-compiler',
    description: 'ReadTheDocs compiler for ARIA documentation',
    urls: {
      https: 'https://gitlab.com/aria-php/rtd-compiler.git',
      ssh: 'git@gitlab.com:aria-php/rtd-compiler.git',
    },
  },
]

const fragmentScreenRepos: Repository[] = [
  {
    name: 'fandanGO-core',
    description: 'Plugin framework foundation',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-core.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-core.git',
    },
  },
  {
    name: 'fandanGO-aria',
    description: 'ARIA integration - auth, token management, metadata submission',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-aria.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-aria.git',
    },
  },
  {
    name: 'fandanGO-cryoem-cnb',
    description: 'CNB-CSIC Madrid cryo-EM plugin (peer reference)',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-cryoem-cnb.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-cryoem-cnb.git',
    },
  },
  {
    name: 'fandanGO-nmr-cerm',
    description: 'CERM Florence NMR plugin (peer reference)',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-nmr-cerm.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-nmr-cerm.git',
    },
  },
  {
    name: 'fandanGO-nmr-guf',
    description: 'GUF Frankfurt NMR plugin (peer reference)',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-nmr-guf.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-nmr-guf.git',
    },
  },
  {
    name: 'Samples',
    description: 'Sample metadata/datasets for community reference',
    urls: {
      https: 'https://github.com/FragmentScreen/Samples.git',
      ssh: 'git@github.com:FragmentScreen/Samples.git',
    },
  },
]

const reposAndRefsConfig: ReposAndRefsConfig = {
  links: {
    docs: 'https://diamondlightsource.github.io/smartem-decisions/',
    projectBoard: 'https://github.com/orgs/DiamondLightSource/projects/51/views/1',
  },
  repositories: [
    {
      org: 'DiamondLightSource',
      orgUrl: 'https://github.com/DiamondLightSource',
      repos: diamondLightSourceRepos,
    },
    {
      org: 'FragmentScreen',
      orgUrl: 'https://github.com/FragmentScreen',
      repos: fragmentScreenRepos,
    },
    {
      org: 'aria-php',
      orgUrl: 'https://gitlab.com/aria-php',
      repos: gitlabAriaPHPRepos,
    },
  ],
}

// =============================================================================
// Microscope List
// =============================================================================

interface CryoEMInstrument {
  name: string
  alias: string
}

const microscopeList: CryoEMInstrument[] = [
  { name: 'Krios 1', alias: 'm02' },
  { name: 'Krios 2', alias: 'm03' },
  { name: 'Krios 3', alias: 'm06' },
  { name: 'Krios 4', alias: 'm07' },
  { name: 'Krios 5', alias: 'm08' },
  { name: 'Talos', alias: 'm04' },
  { name: 'Scios', alias: 'm05' },
  { name: 'Glacios 1', alias: 'm10' },
  { name: 'Glacios 2', alias: 'm12' },
  { name: 'Aquilos', alias: 'm11' },
  { name: 'Leica cryoCLEM', alias: 'm14' },
]

// =============================================================================
// WebUI Config
// =============================================================================

// =============================================================================
// Feature Flags
// =============================================================================

interface FeatureFlags {
    repoStatsInDev: boolean
    repoStatsInProd: boolean
    connectionLineStyle: 'straight' | 'bezier' | 'orthogonal'
}

const featureFlags: FeatureFlags = {
  repoStatsInDev: true,
  repoStatsInProd: true,
  connectionLineStyle: 'bezier',
}

// =============================================================================
// Header Configuration
// =============================================================================

interface HeaderButtonConfig {
  text?: string
  tooltip: string
}

interface HeaderConfig {
  homeButton: HeaderButtonConfig
  docsButton: HeaderButtonConfig
  boardButton: HeaderButtonConfig
  menuButton: HeaderButtonConfig
  omniboxPlaceholder: string
  repoSelectorLabel: string
}

interface WebUiConfig {
  appTitle: string
  header: HeaderConfig
}

const webUiConfig: WebUiConfig = {
  appTitle: 'SmartEM Dev Dashboard',
  header: {
    homeButton: { tooltip: 'Navigate to dashboard home' },
    docsButton: { text: 'docs', tooltip: 'Open project documentation' },
    boardButton: { text: 'board', tooltip: 'Open GitHub project board' },
    menuButton: { tooltip: 'Open settings menu' },
    omniboxPlaceholder: 'search..',
    repoSelectorLabel: 'repos / codebases',
  },
}

// =============================================================================
// Aggregated App Contents
// =============================================================================

export interface WebUiAppContents {
  githubTags: GitHubTagsConfig
  repos: ReposAndRefsConfig
  microscopes: CryoEMInstrument[]
  config: WebUiConfig
  featureFlags: FeatureFlags
}

export const webUiAppContents: WebUiAppContents = {
  githubTags: githubTagsConfig,
  repos: reposAndRefsConfig,
  microscopes: microscopeList,
  config: webUiConfig,
  featureFlags: featureFlags,
}

export default webUiAppContents
