/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/prebuild.ts from:
 * - core/github-tags-config.ts
 * - core/repos-and-refs.ts
 * - core/microscope-list.ts
 * - core/webui-config.ts
 *
 * Edit the source files in core/ and run 'npm run prebuild' to regenerate.
 */

// =============================================================================
// GitHub Tags Config
// =============================================================================

interface GitHubTagsConfig {
  // To be defined
}

const githubTagsConfig: GitHubTagsConfig = {}

// =============================================================================
// Repos and Refs
// =============================================================================

interface RepoUrls {
  https: string
  ssh: string
}

interface Repository {
  name: string
  description: string
  urls: RepoUrls
}

interface OrgRepos {
  org: string
  orgUrl: string
  repos: Repository[]
}

interface ExternalLinks {
  docs: string
  projectBoard: string
}

interface ReposAndRefsConfig {
  links: ExternalLinks
  repositories: OrgRepos[]
}

const diamondLightSourceRepos: Repository[] = [
  {
    name: 'smartem-decisions',
    description: 'Central system controller - backbone, messaging router, persistence, auth',
    urls: {
      https: 'https://github.com/DiamondLightSource/smartem-decisions.git',
      ssh: 'git@github.com:DiamondLightSource/smartem-decisions.git',
    },
  },
  {
    name: 'smartem-frontend',
    description: 'Web UI for SmartEM - user-facing view of acquisition sessions and ML decisions',
    urls: {
      https: 'https://github.com/DiamondLightSource/smartem-frontend.git',
      ssh: 'git@github.com:DiamondLightSource/smartem-frontend.git',
    },
  },
  {
    name: 'smartem-devtools',
    description: 'Developer tooling, documentation, and workspace configuration',
    urls: {
      https: 'https://github.com/DiamondLightSource/smartem-devtools.git',
      ssh: 'git@github.com:DiamondLightSource/smartem-devtools.git',
    },
  },
  {
    name: 'fandanGO-cryoem-dls',
    description: 'DLS facility plugin for FandanGO - bridges SmartEM to ARIA',
    urls: {
      https: 'https://github.com/DiamondLightSource/fandanGO-cryoem-dls.git',
      ssh: 'git@github.com:DiamondLightSource/fandanGO-cryoem-dls.git',
    },
  },
  {
    name: 'cryoem-services',
    description: 'Processing execution layer for cryo-EM data pipelines (reference-only)',
    urls: {
      https: 'https://github.com/DiamondLightSource/cryoem-services.git',
      ssh: 'git@github.com:DiamondLightSource/cryoem-services.git',
    },
  },
]

const fragmentScreenRepos: Repository[] = [
  {
    name: 'fandanGO-core',
    description: 'Plugin framework foundation',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-core.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-core.git',
    },
  },
  {
    name: 'fandanGO-aria',
    description: 'ARIA integration - auth, token management, metadata submission',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-aria.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-aria.git',
    },
  },
  {
    name: 'fandanGO-cryoem-cnb',
    description: 'CNB-CSIC Madrid cryo-EM plugin (peer reference)',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-cryoem-cnb.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-cryoem-cnb.git',
    },
  },
  {
    name: 'fandanGO-nmr-cerm',
    description: 'CERM Florence NMR plugin (peer reference)',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-nmr-cerm.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-nmr-cerm.git',
    },
  },
  {
    name: 'fandanGO-nmr-guf',
    description: 'GUF Frankfurt NMR plugin (peer reference)',
    urls: {
      https: 'https://github.com/FragmentScreen/fandanGO-nmr-guf.git',
      ssh: 'git@github.com:FragmentScreen/fandanGO-nmr-guf.git',
    },
  },
  {
    name: 'Samples',
    description: 'Sample metadata/datasets for community reference',
    urls: {
      https: 'https://github.com/FragmentScreen/Samples.git',
      ssh: 'git@github.com:FragmentScreen/Samples.git',
    },
  },
]

const reposAndRefsConfig: ReposAndRefsConfig = {
  links: {
    docs: 'https://diamondlightsource.github.io/smartem-decisions/',
    projectBoard: 'https://github.com/orgs/DiamondLightSource/projects/33/views/1',
  },
  repositories: [
    {
      org: 'DiamondLightSource',
      orgUrl: 'https://github.com/DiamondLightSource',
      repos: diamondLightSourceRepos,
    },
    {
      org: 'FragmentScreen',
      orgUrl: 'https://github.com/FragmentScreen',
      repos: fragmentScreenRepos,
    },
  ],
}

// =============================================================================
// Microscope List
// =============================================================================

interface CryoEMInstrument {
  name: string
  alias: string
}

const microscopeList: CryoEMInstrument[] = [
  { name: 'Krios 1', alias: 'm02' },
  { name: 'Krios 2', alias: 'm03' },
  { name: 'Krios 3', alias: 'm06' },
  { name: 'Krios 4', alias: 'm07' },
  { name: 'Krios 5', alias: 'm08' },
  { name: 'Talos', alias: 'm04' },
  { name: 'Scios', alias: 'm05' },
  { name: 'Glacios 1', alias: 'm10' },
  { name: 'Glacios 2', alias: 'm12' },
  { name: 'Aquilos', alias: 'm11' },
  { name: 'Leica cryoCLEM', alias: 'm14' },
]

// =============================================================================
// WebUI Config
// =============================================================================

interface WebUiConfig {
  // Reserved for future app-level config
}

const webUiConfig: WebUiConfig = {}

// =============================================================================
// Aggregated App Contents
// =============================================================================

export interface WebUiAppContents {
  githubTags: GitHubTagsConfig
  repos: ReposAndRefsConfig
  microscopes: CryoEMInstrument[]
  config: WebUiConfig
}

export const webUiAppContents: WebUiAppContents = {
  githubTags: githubTagsConfig,
  repos: reposAndRefsConfig,
  microscopes: microscopeList,
  config: webUiConfig,
}

export default webUiAppContents
